### ISSUE TITLE
Rename the command `git-cl` instead of it's current `git-changelog`

### ISSUE THREAD

**Issue by drewdeponte** [uptech/git-cl#11]
I want to do this because adding the shell alias breaks the `git cl` pattern. Maybe we could make something work with an actual Git config alias. But other commands are out there named `git-changelog` and are crappier and I want us to be differentiated by name a bit. Also, I want people to be able to use it the way we think it should be used without having to do any real setup.

**Comment by anthonycastelli** [comment]
#17 Closes this
