### ISSUE TITLE
Possibly add a cli option to recognize pre-release release tags as well.

### ISSUE THREAD

**Issue by drewdeponte** [uptech/git-cl#31]
Could maybe use the `-p` switch to indicate this. I am not sure this is useful but it may be for some people.

**Comment by anthonycastelli** [comment]
I can see it being useful to just get a summary of changes for this release. Since I use pre-release tags I would say this would be helpful for me and I am sure many others.

**Comment by drewdeponte** [comment]
I added this functionality already so I am closing this issue.
