### ISSUE TITLE
git cl full crashes if there are no tags

### ISSUE THREAD

**Issue by chillbrodev** [uptech/git-cl#46]
Crash Log:

```
git cl full
# Changelog
All notable changes to this project will be documented in this file.
The format is based on [Keep a Changelog](https://keepachangelog.com/en/1.0.0/).
Generated by [Git Changelog](https://github.com/uptech/git-cl), an open source project brought to you by [UpTech Works, LLC](https://upte.ch). A consultancy that partners with companies to help **build**, **launch**, and **refine** their products.

Fatal error: 'try!' expression unexpectedly raised an error: GitChangelog.GitShell.Error.gitLogFailure: file /private/tmp/git-cl-20200720-57874-2xqokh/Sources/GitChangelog/Models/ReleaseDetails.swift, line 19
error: git-cl died of signal 4
```

Git Version: 2.29.2
Git-CL Version: 3.3.1

Reproduction Steps:

- Make a new git repo, can be local
- Make a commit with changelog information
- Run git cl full
- Observe crash

**Comment by drewdeponte** [comment]
I am trying to reproduce this but am not seeing the crash happen. I am using `v3.3.2`. @chillbrodev would you please check which version of git-cl you are running and see this issue? If it is an earlier version you are seeing the issue with. You should probably update to the latest and see if you are still having the issue.

**Comment by chillbrodev** [comment]
@drewdeponte I ran git --version and got `git version 2.29.2`. Guess I should update and try again. I added my version to the issue.

**Comment by chillbrodev** [comment]
@drewdeponte Okay cool, I updated to `v3.3.2` and it works. Will close this out. Thanks for the help.
